### ISSUE TITLE
Allow external addresses in `AccountSelect`

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#403]
Users should be able to paste the address of a contract in the account select for a param of `AccountId` type. The UI should validate the address and check if it's on-chain and display the result to the user

**Comment by Maar-io** [comment]
This issue is blocker for contract interaction in many cases. Say you minted a token and want to send it to someone other than predefine Dev accounts. You can't since account dropdown supports only imported accounts and not external.
Since Polkadot-js-UI is broken for Contract interaction for quite some time (after introduction of Weights V2), the whole Polkadot contract ecosystem is affected by this issue. 
Please raise the priority for this one.

**Comment by statictype** [comment]
Understood, will try to squeeze it in on the weekend
