### ISSUE TITLE
Allow users to change metadata when instantiating from hash

### ISSUE THREAD

**Issue by statictype** [paritytech/contracts-ui#457]
Right now when instantiating from hash or re-instantiating we pre-fill the file input with the stored metadata associated with the hash.

<img width="500" alt="Screenshot 2023-03-29 at 12 39 54" src="https://user-images.githubusercontent.com/42985153/228509133-622d0d85-1180-4b7a-aeaa-804be5bbca49.png">

Would be nice to allow users to add a different metadata file. Similar to how the update metadata case is handled, we could display an `x` that removes the contents of the file input.

<img width="382" alt="Screenshot 2023-03-29 at 12 40 17" src="https://user-images.githubusercontent.com/42985153/228509431-d087c095-3a90-47ad-aeec-972d38f877f0.png">

Note: the metadata here will be associated with the new contract instance. the code "bundle" stays associated with metadata it was first instantiated with.

**Comment by CharliePops** [comment]
Hey @statictype , I've playing around with the UI and I agree that this would be a nice UX improvement. I can address this issue though I have one question. 

What would be the expected behavior if the user removes the file(click the `x` button)? shoud we revert the metadata information to the previous state(the original code hash) or just remove completely any metadata and force the user to select a new file or hash?

I can make a pull request for this, let me know.

**Comment by statictype** [comment]
@CharliePops I think I misunderstood, the behaviour in the PR is what we want. no need for changes

**Comment by CharliePops** [comment]
Awesome 👍🏼
